export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL';


// export const DELETE_QUESTIONS_SUCCESS = 'DELETE_QUESTIONS_SUCCESS';
// export const DELETE_QUESTIONS_FAIL = 'DELETE_QUESTIONS_FAIL';
